import { defineTable } from "convex/server";
import { v } from "convex/values";
import {
  statuses,
  eligibility,
  listingRanges,
} from "../src/lib/campaigns/model";
export const campaignTables = {
  marketing_campaigns: defineTable({
    name: v.string(),
    slug: v.string(),
    type: v.literal("realtor_giveaway"),
    status: v.union(...statuses.map(v.literal)),
    public_title: v.string(),
    public_description: v.string(),
    prize_name: v.string(),
    prize_value_cents: v.number(),
    currency: v.literal("CAD"),
    starts_at: v.number(),
    closes_at: v.number(),
    timezone: v.literal("America/Vancouver"),
    eligibility_summary: v.string(),
    eligible_cities: v.array(v.string()),
    eligible_province: v.optional(v.literal("BC")),
    official_rules: v.string(),
    rules_version: v.string(),
    privacy_notice: v.string(),
    consent_text: v.string(),
    prize_terms: v.string(),
    prize_terms_version: v.string(),
    prize_expires_at: v.optional(v.number()),
    expiry_months_after_confirmation: v.optional(v.literal(6)),
    skill_question_required: v.boolean(),
    assigned_to: v.id("users"),
    legal_approved: v.boolean(),
    created_by: v.id("users"),
    created_at: v.number(),
    updated_at: v.number(),
    version: v.number(),
    closed_at: v.optional(v.number()),
    draw_completed_at: v.optional(v.number()),
    active_draw_id: v.optional(v.id("campaign_draws")),
  })
    .index("by_slug", ["slug"])
    .index("by_status", ["status"]),
  campaign_entries: defineTable({
    campaign_id: v.id("marketing_campaigns"),
    realtor_id: v.union(v.id("realtors"), v.null()),
    normalized_email: v.string(),
    normalized_phone: v.string(),
    // Professional details are retained only for unresolved identity conflicts; normal entries join the CRM.
    pending_contact: v.optional(
      v.object({
        first_name: v.string(),
        last_name: v.string(),
        brokerage: v.string(),
        city: v.string(),
      }),
    ),
    entered_at: v.number(),
    source: v.string(),
    source_detail: v.string(),
    event_day: v.string(),
    rules_version: v.string(),
    rules_accepted_at: v.number(),
    marketing_consent: v.boolean(),
    marketing_consent_at: v.optional(v.number()),
    annual_listings: v.union(...listingRanges.map(v.literal)),
    licensed_realtor: v.boolean(),
    licensed_in_bc: v.optional(v.boolean()),
    city_at_entry: v.string(),
    crm_origin: v.union(
      v.literal("new"),
      v.literal("existing"),
      v.literal("review"),
    ),
    eligibility_status: v.union(...eligibility.map(v.literal)),
    eligibility_reason: v.string(),
    draw_status: v.union(
      v.literal("not_selected"),
      v.literal("selected"),
      v.literal("confirmed"),
      v.literal("disqualified"),
    ),
    selected_at: v.optional(v.number()),
    confirmed_at: v.optional(v.number()),
    confirmed_by: v.optional(v.id("users")),
    disqualified_at: v.optional(v.number()),
    disqualification_reason: v.optional(v.string()),
    verification_note: v.optional(v.string()),
    created_at: v.number(),
    updated_at: v.number(),
    version: v.number(),
  })
    .index("by_campaign", ["campaign_id", "entered_at"])
    .index("by_email", ["campaign_id", "normalized_email"])
    .index("by_phone", ["campaign_id", "normalized_phone"])
    .index("by_realtor_campaign", ["realtor_id", "campaign_id"]),
  campaign_draws: defineTable({
    campaign_id: v.id("marketing_campaigns"),
    rules_version: v.string(),
    closed_at: v.number(),
    entry_ids: v.array(v.id("campaign_entries")),
    eligible_count: v.number(),
    operator_id: v.id("users"),
    created_at: v.number(),
    algorithm: v.literal("node-crypto-randomInt-v1"),
    reason: v.string(),
    previous_draw_id: v.optional(v.id("campaign_draws")),
    selected_entry_id: v.optional(v.id("campaign_entries")),
    completed_at: v.optional(v.number()),
  }).index("by_campaign", ["campaign_id", "created_at"]),
  campaign_awards: defineTable({
    campaign_id: v.id("marketing_campaigns"),
    entry_id: v.id("campaign_entries"),
    original_cents: v.number(),
    remaining_cents: v.number(),
    currency: v.literal("CAD"),
    issued_at: v.number(),
    expires_at: v.number(),
    terms_version: v.string(),
    terms: v.string(),
    status: v.literal("issued_unapplied"),
    issued_by: v.id("users"),
  }).index("by_campaign", ["campaign_id"]),
  campaign_rate_windows: defineTable({
    key: v.string(),
    count: v.number(),
    expires_at: v.number(),
  })
    .index("by_key", ["key"])
    .index("by_expiry", ["expires_at"]),
};
